# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Podmin < Formula
  desc "Minimal, secure container platform"
  homepage "https://podmin.dev"
  version "0.13.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/podmin-dev/podmin/releases/download/v0.13.0/podmin_0.13.0_darwin_amd64.tar.gz"
      sha256 "966b3a19facfa69891b7224183d1173c7ccb1473a9f6e180e6f9dfcc2a787cc3"

      define_method(:install) do
        bin.install "podmin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/podmin-dev/podmin/releases/download/v0.13.0/podmin_0.13.0_darwin_arm64.tar.gz"
      sha256 "d419e7dbb412097509100a18f0b460f87286bfbb18dcbd1514cab8cf5ebfb573"

      define_method(:install) do
        bin.install "podmin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/podmin-dev/podmin/releases/download/v0.13.0/podmin_0.13.0_linux_amd64.tar.gz"
      sha256 "53483be8e5c1887f5b0224f1821d98cb60857ce7497ade9878c21adc6849948b"
      define_method(:install) do
        bin.install "podmin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/podmin-dev/podmin/releases/download/v0.13.0/podmin_0.13.0_linux_arm64.tar.gz"
      sha256 "1fafa2616e786169ea359bf7bc39f7cd9d7466e0a7f10e8a96bb3f9703f3eac1"
      define_method(:install) do
        bin.install "podmin"
      end
    end
  end

  test do
    system "#{bin}/podmin --version"
  end
end
