# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Podmin < Formula
  desc "Minimal, secure container platform"
  homepage "https://podmin.dev"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/podmin-dev/podmin/releases/download/v0.1.0/podmin_0.1.0_darwin_amd64.tar.gz"
      sha256 "873b748782417ffe325ae5b3b1928b66748f93aab206547561aa7dd6b9b9689d"

      define_method(:install) do
        bin.install "podmin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/podmin-dev/podmin/releases/download/v0.1.0/podmin_0.1.0_darwin_arm64.tar.gz"
      sha256 "d637205332c9dab0782094d50662ba635d1d7d916f55871e2b058c4b6c141c8d"

      define_method(:install) do
        bin.install "podmin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/podmin-dev/podmin/releases/download/v0.1.0/podmin_0.1.0_linux_amd64.tar.gz"
      sha256 "d37338702c251f351632379ac1084f3292d4dd0002dabd356180e061dc1d72e7"
      define_method(:install) do
        bin.install "podmin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/podmin-dev/podmin/releases/download/v0.1.0/podmin_0.1.0_linux_arm64.tar.gz"
      sha256 "c51e1b6c045a72a672d399cfa40c6df903085bfebd47cb536ca70f85e4187cd5"
      define_method(:install) do
        bin.install "podmin"
      end
    end
  end

  test do
    system "#{bin}/podmin --version"
  end
end
